// =========================================================== User Reducer Types
export const LOGOUT_SITE = "LOGOUT_SITE";
export const GET_USER_START = "GET_USER_START";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const GET_USERS_START = "GET_USERS_START";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const UPDATE_PHOTO_START = "UPDATE_PHOTO_START";
export const UPDATE_PHOTO_SUCCESS = "UPDATE_PHOTO_SUCCESS";
export const UPDATE_PHOTO_ERROR = "UPDATE_PHOTO_ERROR";
export const NEW_USER_START = "NEW_USER_START";
export const NEW_USER_SUCCESS = "NEW_USER_SUCCESS";
export const NEW_USER_ERROR = "NEW_USER_ERROR";
export const CREATE_PROFILE_START = "CREATE_PROFILE_START";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_ERROR = "CREATE_PROFILE_ERROR";

// =========================================================== Payment Reducer Types
export const PAY_TIP_START = "PAY_TIP_START";
export const PAY_TIP_SUCCESS = "PAY_TIP_SUCCESS";
export const PAY_TIP_ERROR = "PAY_TIP_ERROR";
export const RESET_PAYMENT_FORM = "RESET_PAYMENT_FORM";
